baseURL: "https://miroir-blog.netlify.app/"  # ← Change this to your actual domain or Netlify URL
languageCode: "en-us"
title: "Miroir Blog"
theme: "PaperMod"

pagination:
  pagerSize: 10
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  env: production
  description: "A blog of reflections, truth, and authentic thoughts."
  author: "Fils Jean Pierre"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: false
  defaultTheme: auto
  disableThemeToggle: false
  socialIcons:
    - name: github
      url: "https://github.com/mutsinzifjp"
    - name: Instagram
      url: "https://www.instagram.com/fils_brandy/"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/fils-jean-pierre-mutsinzi/"
    - name: X (twitter)
      url: "https://x.com/Mutsinzifjp2"
    - name: email
      url: "mailto:mutsinzifjp@gmail.com"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    noClasses: false
