backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Site-wide settings for theme and design customization
collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "design"
        label: "Design & Theme Settings"
        file: "data/design.yml"
        fields:
          - label: "Theme Selection"
            name: "theme"
            widget: "object"
            fields:
              - { label: "Current Theme", name: "current", widget: "select", options: ["PaperMod", "Ananke", "Hugo-theme-stack", "LoveIt", "DoIt", "custom"], default: "PaperMod" }
              - { label: "Custom CSS", name: "custom_css", widget: "code", default_language: "css", required: false }
              - { label: "Custom Theme Name", name: "custom_name", widget: "string", required: false }
          - label: "Color Scheme"
            name: "colors"
            widget: "object"
            fields:
              - { label: "Primary Color", name: "primary", widget: "color", default: "#1976d2" }
              - { label: "Secondary Color", name: "secondary", widget: "color", default: "#dc004e" }
              - { label: "Background Color", name: "background", widget: "color", default: "#ffffff" }
              - { label: "Text Color", name: "text", widget: "color", default: "#212529" }
              - { label: "Link Color", name: "link", widget: "color", default: "#0d6efd" }
              - { label: "Dark Mode Primary", name: "dark_primary", widget: "color", default: "#90caf9" }
              - { label: "Dark Mode Background", name: "dark_background", widget: "color", default: "#121212" }
              - { label: "Dark Mode Text", name: "dark_text", widget: "color", default: "#ffffff" }
          - label: "Typography"
            name: "fonts"
            widget: "object"
            fields:
              - { label: "Heading Font", name: "heading", widget: "select", options: ["Roboto", "Open Sans", "Lato", "Montserrat", "Playfair Display", "Merriweather", "Source Sans Pro", "custom"], default: "Roboto" }
              - { label: "Body Font", name: "body", widget: "select", options: ["Roboto", "Open Sans", "Lato", "Montserrat", "Source Sans Pro", "PT Sans", "Nunito", "custom"], default: "Open Sans" }
              - { label: "Monospace Font", name: "mono", widget: "select", options: ["Fira Code", "Source Code Pro", "JetBrains Mono", "Monaco", "Consolas", "custom"], default: "Fira Code" }
              - { label: "Custom Heading Font URL", name: "custom_heading_url", widget: "string", required: false }
              - { label: "Custom Body Font URL", name: "custom_body_url", widget: "string", required: false }
              - { label: "Font Size Scale", name: "scale", widget: "select", options: ["small", "medium", "large"], default: "medium" }
          - label: "Layout Options"
            name: "layout"
            widget: "object"
            fields:
              - { label: "Homepage Layout", name: "homepage", widget: "select", options: ["grid", "list", "carousel", "reel", "masonry"], default: "list" }
              - { label: "Post List Layout", name: "post_list", widget: "select", options: ["grid", "list", "cards", "timeline"], default: "list" }
              - { label: "Single Post Layout", name: "single_post", widget: "select", options: ["centered", "wide", "sidebar", "magazine"], default: "centered" }
              - { label: "Grid Columns", name: "grid_columns", widget: "select", options: ["2", "3", "4"], default: "3" }
              - { label: "Show Sidebar", name: "sidebar", widget: "boolean", default: true }
              - { label: "Container Width", name: "container_width", widget: "select", options: ["narrow", "medium", "wide", "full"], default: "medium" }
          - label: "Animation & Effects"
            name: "animations"
            widget: "object"
            fields:
              - { label: "Enable Animations", name: "enabled", widget: "boolean", default: true }
              - { label: "Page Transitions", name: "page_transitions", widget: "boolean", default: true }
              - { label: "Hover Effects", name: "hover_effects", widget: "boolean", default: true }
              - { label: "Scroll Animations", name: "scroll_animations", widget: "boolean", default: true }
              - { label: "Loading Animations", name: "loading_animations", widget: "boolean", default: true }
              - { label: "Animation Speed", name: "speed", widget: "select", options: ["slow", "normal", "fast"], default: "normal" }
              - { label: "Parallax Effects", name: "parallax", widget: "boolean", default: false }
          - label: "Advanced Features"
            name: "features"
            widget: "object"
            fields:
              - { label: "Dark Mode Toggle", name: "dark_mode", widget: "boolean", default: true }
              - { label: "Reading Progress Bar", name: "reading_progress", widget: "boolean", default: true }
              - { label: "Back to Top Button", name: "back_to_top", widget: "boolean", default: true }
              - { label: "Social Sharing", name: "social_sharing", widget: "boolean", default: true }
              - { label: "Reading Time", name: "reading_time", widget: "boolean", default: true }
              - { label: "Table of Contents", name: "toc", widget: "boolean", default: true }
              - { label: "Search Functionality", name: "search", widget: "boolean", default: true }
              - { label: "Comments System", name: "comments", widget: "select", options: ["none", "disqus", "utterances", "giscus"], default: "none" }

  # Enhanced Blog Posts
  - name: "post"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Description/Summary", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Last Modified", name: "lastmod", widget: "datetime", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Featured Post", name: "featured", widget: "boolean", default: false }
      - { label: "Author", name: "author", widget: "string", default: "Fils Jean Pierre" }
      - label: "Authors (Multiple)"
        name: "authors"
        widget: "list"
        required: false
        field: { label: "Author", name: "author", widget: "string" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Image Caption", name: "image_caption", widget: "string", required: false }
      - { label: "Image Alt Text", name: "image_alt", widget: "string", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - label: "SEO & Meta"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Meta Title", name: "title", widget: "string", required: false }
          - { label: "Meta Description", name: "description", widget: "text", required: false }
          - { label: "Keywords", name: "keywords", widget: "list", required: false }
          - { label: "Canonical URL", name: "canonical", widget: "string", required: false }
      - label: "Social Media"
        name: "social"
        widget: "object"
        required: false
        fields:
          - { label: "Twitter Card Type", name: "twitter_card", widget: "select", options: ["summary", "summary_large_image"], default: "summary_large_image" }
          - { label: "Open Graph Image", name: "og_image", widget: "image", required: false }
          - { label: "Twitter Image", name: "twitter_image", widget: "image", required: false }
      - label: "Post Settings"
        name: "settings"
        widget: "object"
        required: false
        fields:
          - { label: "Show Table of Contents", name: "toc", widget: "boolean", default: true }
          - { label: "Show Reading Time", name: "reading_time", widget: "boolean", default: true }
          - { label: "Show Social Sharing", name: "social_sharing", widget: "boolean", default: true }
          - { label: "Enable Comments", name: "comments", widget: "boolean", default: true }
          - { label: "Layout Type", name: "layout", widget: "select", options: ["default", "wide", "minimal", "magazine"], default: "default" }
          - { label: "Animation Style", name: "animation", widget: "select", options: ["none", "fade", "slide", "zoom"], default: "fade" }
      - { label: "Content", name: "body", widget: "markdown", buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "code-block", "bulleted-list", "numbered-list"] }
      - label: "Custom CSS"
        name: "custom_css"
        widget: "code"
        default_language: "css"
        required: false
      - label: "Custom JavaScript"
        name: "custom_js"
        widget: "code"
        default_language: "javascript"
        required: false

  # Enhanced Video Posts
  - name: "videos"
    label: "Video Posts"
    folder: "content/videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "videos/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Author", name: "author", widget: "string", default: "Fils Jean Pierre" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - label: "Video Settings"
        name: "video"
        widget: "object"
        fields:
          - { label: "Video URL", name: "url", widget: "string" }
          - { label: "Video Platform", name: "platform", widget: "select", options: ["youtube", "vimeo", "twitch", "dailymotion", "custom"], default: "youtube" }
          - { label: "Video ID", name: "id", widget: "string", required: false }
          - { label: "Autoplay", name: "autoplay", widget: "boolean", default: false }
          - { label: "Show Controls", name: "controls", widget: "boolean", default: true }
          - { label: "Loop", name: "loop", widget: "boolean", default: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Video Duration", name: "duration", widget: "string", required: false }
      - label: "Video Settings"
        name: "settings"
        widget: "object"
        required: false
        fields:
          - { label: "Layout Type", name: "layout", widget: "select", options: ["default", "wide", "theater"], default: "default" }
          - { label: "Show Transcript", name: "transcript", widget: "boolean", default: false }
          - { label: "Animation Style", name: "animation", widget: "select", options: ["none", "fade", "slide", "zoom"], default: "fade" }
      - { label: "Content", name: "body", widget: "markdown", required: false }

  # Enhanced Newsletters
  - name: "newsletters"
    label: "Newsletters"
    folder: "content/newsletters" 
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "newsletters/{{slug}}"
    fields:
      - { label: "Subject", name: "title", widget: "string" }
      - { label: "Issue Number", name: "issue", widget: "number", required: false }
      - { label: "Send Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: "Fils Jean Pierre" }
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        field: { label: "Category", name: "category", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        field: { label: "Tag", name: "tag", widget: "string" }
      - { label: "Preview Text", name: "preview", widget: "text", required: false }
      - { label: "Header Image", name: "header_image", widget: "image", required: false }
      - label: "Newsletter Settings"
        name: "settings"
        widget: "object"
        required: false
        fields:
          - { label: "Template Style", name: "template", widget: "select", options: ["modern", "classic", "minimal", "bold"], default: "modern" }
          - { label: "Include Social Links", name: "social_links", widget: "boolean", default: true }
          - { label: "Include Unsubscribe", name: "unsubscribe", widget: "boolean", default: true }
          - { label: "Track Opens", name: "track_opens", widget: "boolean", default: true }
          - { label: "Track Clicks", name: "track_clicks", widget: "boolean", default: true }
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        fields:
          - { label: "Section Title", name: "title", widget: "string" }
          - { label: "Section Type", name: "type", widget: "select", options: ["text", "featured_post", "post_list", "image", "cta", "divider"], default: "text" }
          - { label: "Content", name: "content", widget: "markdown", required: false }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "CTA Text", name: "cta_text", widget: "string", required: false }
          - { label: "CTA URL", name: "cta_url", widget: "string", required: false }
      - { label: "Main Content", name: "body", widget: "markdown" }

  # Page Management
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    filter: { field: "type", value: "page" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Type", name: "type", widget: "hidden", default: "page" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - label: "Page Settings"
        name: "settings"
        widget: "object"
        required: false
        fields:
          - { label: "Layout", name: "layout", widget: "select", options: ["default", "wide", "minimal", "landing"], default: "default" }
          - { label: "Show in Menu", name: "menu", widget: "boolean", default: false }
          - { label: "Menu Weight", name: "menu_weight", widget: "number", required: false }
          - { label: "Hide Title", name: "hide_title", widget: "boolean", default: false }
      - { label: "Content", name: "body", widget: "markdown" }
