backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
  - name: "videos"
    label: "Video Posts"
    folder: "content/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video URL", name: "video_url", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
  - name: "newsletters"
    label: "Newsletters"
    folder: "content/newsletters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Subject", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
